site_name: Helpers Documents
site_url: https://docs.rodevs.com/
repo_url: https://docs.rodevs.com
repo_name: "| RoDevs Helpers Department"
copyright: By Rodevs Helper Department. Not affiliated with Roblox or Discord.
site_description: Rodevs Helpers Documents, a place where you can learn multiple things about developing from our incredible helpers.

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - meta_tag.js

theme:
    icon:
      repo: fontawesome/brands/discord
    logo: whiteicon.png
    favicon: bidenrose.png
    language: en
    name: material
    custom_dir: material/.overrides
    font:
      text: Roboto
      code: JetBrains Mono
    palette:
      -  scheme: slate
         toggle:
           icon: material/weather-sunny
           name: Switch to light mode
         primary: black
         accent: purple
      -  scheme: default
         toggle:
           icon: material/weather-night
           name: Switch to dark mode
         primary: blue
         accent: deep orange
      
      #light
      
    features:
      - announce.dismiss
      - navigation.top
      - navigation.tabs
      - navigation.indexes
      - navigation.footer
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
    cookies:
      analytics:
        name: Google Analytics
        checked: true
  analytics:
    provider: google
    property: G-DK4D1FN7GD
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: Yep! This guide was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: This guide could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by sharing your views.
            
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rodevs
      name: Join the discord server!
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/RoDevsWorld
      name: Follow us on twitter!

markdown_extensions:
  - attr_list
  - abbr
  - def_list
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.highlight
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.arithmatex:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - awesome-pages
  #- blogging:
  #    dirs: # The directories to be included
  #      - Updates
  #    features:
  #      tags: {}
  #      locale: en         # The locale for time localizations, default: system's locale
  #    time_format: '%Y-%m-%d %H:%M:%S' # The format used to display the time
  #    meta_time_format: '%Y-%m-%d %H:%M:%S' # The format used to parse the time from meta
  #   theme:
  #      name: card
  - blog
  #- social:
  #    cards_color:
  #      fill: "#0FF1CE" 
  #      text: "#FFFFFF"
  
nav:
  - Home: index.md
  - Scripting:
    - ... | flat | scripting/*.md
    # - scripting/home.md
    - Basic-Courses:
      - scripting/Basic-Courses/Introduction_To_Studio.md
      - scripting/Basic-Courses/Variables.md
      - scripting/Basic-Courses/Strings.md
      - scripting/Basic-Courses/operators.md
      - scripting/Basic-Courses/basics_of_properties.md
      - scripting/Basic-Courses/If_statements.md
      - scripting/Basic-Courses/basic_loops.md
    - Intermediate-Courses:
      - scripting/Intermediate-Courses/Basics_of_Functions.md
      - scripting/Intermediate-Courses/Tables.md
      - scripting/Intermediate-Courses/handling_events.md
      - scripting/Intermediate-Courses/Scripts_and_Local_scripts.md
      - scripting/Intermediate-Courses/Players_Service.md
      - scripting/Intermediate-Courses/Character.md
      - scripting/Intermediate-Courses/Tool.md
      - scripting/Intermediate-Courses/modules.md
      - scripting/Intermediate-Courses/Vector3.md
      - scripting/Intermediate-Courses/Position_and_Size.md
      - scripting/Intermediate-Courses/Tweening.md
      - scripting/Intermediate-Courses/Attributes.md
      - scripting/Intermediate-Courses/Data_Stores.md
      - scripting/Intermediate-Courses/ContextActionService.md
      - scripting/Intermediate-Courses/Collection_Service.md
      - scripting/Intermediate-Courses/selection_and_highlights.md
      - scripting/Intermediate-Courses/Remote_Events_And_Functions.md
      - scripting/Intermediate-Courses/Bindable_events_and_functions.md
      - scripting/Intermediate-Courses/intro_of_ui.md
      - scripting/Intermediate-Courses/RayCasting.md
      - scripting/Intermediate-Courses/globals.md
    - Advanced-Courses:
      - scripting/Advanced-Courses/Vector3_Part_2.md
      - scripting/Advanced-Courses/more_about_functions.md
      - scripting/Advanced-Courses/More_on_Dictionaries.md
      - scripting/Advanced-Courses/metatables.md
      - scripting/Advanced-Courses/HttpService.md
      - scripting/Advanced-Courses/Inheritance.md
    # - ... | flat | scripting/*.md # not sorted yet
  - Blog:
    - blog/index.md
  - ...
  - Updates:
      - updates/index.md
  - Others:
    - ... | flat | others/*.md # not sorted yet
  - Faq: faq/index.md